// ============================================================================
// TECHNOLOGY_CATEGORIES
// Maps canonical technology names (as produced by technology-aliases.ts)
// to a canonical skill category, used to populate skills.* buckets across
// both the Resume Pipeline and the Job Pipeline.
//
// - Keys are canonical technology names ONLY (never raw aliases).
// - Each canonical technology belongs to exactly ONE category.
// - No functions, no regex, no fuzzy matching — static mapping only.
// ============================================================================

export const TECHNOLOGY_CATEGORIES = {
  // ==========================================================================
  // PROGRAMMING LANGUAGES
  // ==========================================================================
  "ABAP": "languages",
  "Assembly": "languages",
  "Bash": "languages",
  "C": "languages",
  "C#": "languages",
  "C++": "languages",
  "CircuitPython": "languages",
  "Clojure": "languages",
  "COBOL": "languages",
  "CoffeeScript": "languages",
  "Crystal": "languages",
  "Dart": "languages",
  "Delphi": "languages",
  "ECMAScript": "languages",
  "Elixir": "languages",
  "Elm": "languages",
  "Erlang": "languages",
  "ES6": "languages",
  "F#": "languages",
  "Fortran": "languages",
  "Go": "languages",
  "Groovy": "languages",
  "Haskell": "languages",
  "Haxe": "languages",
  "Java": "languages",
  "Java Development Kit": "languages",
  "Java Runtime Environment": "languages",
  "Java Virtual Machine": "languages",
  "JavaScript": "languages",
  "Julia": "languages",
  "Kotlin": "languages",
  "Lisp": "languages",
  "Lua": "languages",
  "MATLAB": "languages",
  "MicroPython": "languages",
  "Nim": "languages",
  "Objective-C": "languages",
  "OCaml": "languages",
  "Pascal": "languages",
  "Perl": "languages",
  "PHP": "languages",
  "PowerShell": "languages",
  "Prolog": "languages",
  "Python": "languages",
  "R": "languages",
  "Ruby": "languages",
  "Rust": "languages",
  "SAS": "languages",
  "Scala": "languages",
  "Scheme": "languages",
  "Shell Scripting": "languages",
  "Solidity": "languages",
  "SQL": "languages",
  "Swift": "languages",
  "TypeScript": "languages",
  "VB.NET": "languages",
  "VBA": "languages",
  "Visual Basic": "languages",
  "Zig": "languages",
  "Zsh": "languages",

  // ==========================================================================
  // FRONTEND
  // ==========================================================================
  "Alpine.js": "frontend",
  "Angular": "frontend",
  "AngularJS": "frontend",
  "Ant Design": "frontend",
  "Apollo Client": "frontend",
  "Astro": "frontend",
  "Backbone.js": "frontend",
  "Bootstrap": "frontend",
  "Bulma": "frontend",
  "Chakra UI": "frontend",
  "Chart.js": "frontend",
  "class-variance-authority": "frontend",
  "Create React App": "frontend",
  "CSS": "frontend",
  "CSS3": "frontend",
  "D3.js": "frontend",
  "Ember.js": "frontend",
  "Formik": "frontend",
  "Foundation": "frontend",
  "Framer Motion": "frontend",
  "Gatsby": "frontend",
  "GSAP": "frontend",
  "Headless UI": "frontend",
  "Highcharts": "frontend",
  "HTML": "frontend",
  "HTML5": "frontend",
  "htmx": "frontend",
  "Jotai": "frontend",
  "jQuery": "frontend",
  "Less": "frontend",
  "Lit": "frontend",
  "Lucide Icons": "frontend",
  "Material Design": "frontend",
  "Material UI": "frontend",
  "MobX": "frontend",
  "next-i18next": "frontend",
  "next-intl": "frontend",
  "next-pwa": "frontend",
  "next-seo": "frontend",
  "Next.js": "frontend",
  "Next.js API Routes": "frontend",
  "Next.js App Router": "frontend",
  "Next.js Pages Router": "frontend",
  "NgRx": "frontend",
  "Nuxt.js": "frontend",
  "Pinia": "frontend",
  "PostCSS": "frontend",
  "Preact": "frontend",
  "PrimeNG": "frontend",
  "PrimeReact": "frontend",
  "Quasar": "frontend",
  "Qwik": "frontend",
  "Radix UI": "frontend",
  "React Context API": "frontend",
  "React DOM": "frontend",
  "React Hook Form": "frontend",
  "React Router": "frontend",
  "React Server Components": "frontend",
  "React Suspense": "frontend",
  "React.js": "frontend",
  "Recharts": "frontend",
  "Recoil": "frontend",
  "Redux": "frontend",
  "Redux Toolkit": "frontend",
  "Remix": "frontend",
  "Sass": "frontend",
  "Semantic UI": "frontend",
  "shadcn/ui": "frontend",
  "SolidJS": "frontend",
  "Stylus": "frontend",
  "Svelte": "frontend",
  "SvelteKit": "frontend",
  "SWR": "frontend",
  "Tailwind CSS": "frontend",
  "tailwind-merge": "frontend",
  "TanStack": "frontend",
  "TanStack Form": "frontend",
  "TanStack Query": "frontend",
  "TanStack Router": "frontend",
  "TanStack Start": "frontend",
  "TanStack Table": "frontend",
  "TanStack Virtual": "frontend",
  "Three.js": "frontend",
  "Vue.js": "frontend",
  "Vuetify": "frontend",
  "Vuex": "frontend",
  "Web Components": "frontend",
  "XState": "frontend",
  "Zustand": "frontend",

  // ==========================================================================
  // BACKEND
  // ==========================================================================
  ".NET": "backend",
  ".NET Core": "backend",
  ".NET Framework": "backend",
  "Active Directory": "backend",
  "Actix": "backend",
  "Actix Web": "backend",
  "AdonisJS": "backend",
  "Ajv": "backend",
  "Apache ActiveMQ": "backend",
  "Apache Kafka": "backend",
  "Apache Pulsar": "backend",
  "Apache Tomcat": "backend",
  "ASP.NET": "backend",
  "ASP.NET Core": "backend",
  "Auth.js": "backend",
  "Auth0": "backend",
  "Azure Active Directory": "backend",
  "Beego": "backend",
  "Bun": "backend",
  "Clerk": "backend",
  "CodeIgniter": "backend",
  "Deno": "backend",
  "Django": "backend",
  "Django REST Framework": "backend",
  "Echo": "backend",
  "Express.js": "backend",
  "FastAPI": "backend",
  "Fastify": "backend",
  "Fiber": "backend",
  "Firebase Authentication": "backend",
  "Flask": "backend",
  "Gin": "backend",
  "GraphQL": "backend",
  "gRPC": "backend",
  "Gunicorn": "backend",
  "Hapi.js": "backend",
  "Identity and Access Management": "backend",
  "Joi": "backend",
  "JSON-RPC": "backend",
  "JWT": "backend",
  "Keycloak": "backend",
  "Koa.js": "backend",
  "Laravel": "backend",
  "LDAP": "backend",
  "Micronaut": "backend",
  "NATS": "backend",
  "NestJS": "backend",
  "NestJS CLI": "backend",
  "NestJS Microservices": "backend",
  "NextAuth.js": "backend",
  "Node.js": "backend",
  "OAuth 2.0": "backend",
  "Okta": "backend",
  "OpenAPI": "backend",
  "OpenID Connect": "backend",
  "Passport.js": "backend",
  "Phoenix Framework": "backend",
  "Ping Identity": "backend",
  "Pyramid": "backend",
  "Quarkus": "backend",
  "RabbitMQ": "backend",
  "REST API": "backend",
  "Rocket": "backend",
  "Ruby on Rails": "backend",
  "SAML": "backend",
  "Server-Sent Events": "backend",
  "Sinatra": "backend",
  "SOAP": "backend",
  "Socket.IO": "backend",
  "Spring Boot": "backend",
  "Spring Framework": "backend",
  "Spring MVC": "backend",
  "Supabase Auth": "backend",
  "Supabase Edge Functions": "backend",
  "SuperTokens": "backend",
  "Swagger": "backend",
  "Swagger UI": "backend",
  "Symfony": "backend",
  "Tornado": "backend",
  "tRPC": "backend",
  "Uvicorn": "backend",
  "WebRTC": "backend",
  "WebSocket": "backend",
  "Yii": "backend",
  "Yup": "backend",
  "ZeroMQ": "backend",
  "Zod": "backend",

  // ==========================================================================
  // DATABASE
  // ==========================================================================
  "Active Record": "database",
  "Algolia": "database",
  "Amazon Aurora": "database",
  "Amazon DynamoDB": "database",
  "Amazon Neptune": "database",
  "Amazon Redshift": "database",
  "Apache Cassandra": "database",
  "Apache HBase": "database",
  "Apache Solr": "database",
  "ArangoDB": "database",
  "Azure Cosmos DB": "database",
  "Chroma": "database",
  "ClickHouse": "database",
  "Cloud Firestore": "database",
  "Cloudflare D1": "database",
  "Cloudflare Workers KV": "database",
  "CockroachDB": "database",
  "Couchbase": "database",
  "CouchDB": "database",
  "Dgraph": "database",
  "Drizzle ORM": "database",
  "DuckDB": "database",
  "EdgeDB": "database",
  "Elasticsearch": "database",
  "Entity Framework": "database",
  "Entity Framework Core": "database",
  "Epsilla": "database",
  "Firebase Realtime Database": "database",
  "Google BigQuery": "database",
  "GORM": "database",
  "Hibernate": "database",
  "IBM Db2": "database",
  "InfluxDB": "database",
  "Key-Value Store": "database",
  "Knex.js": "database",
  "LanceDB": "database",
  "LevelDB": "database",
  "LibSQL": "database",
  "MariaDB": "database",
  "Marqo": "database",
  "Meilisearch": "database",
  "Memcached": "database",
  "Microsoft SQL Server": "database",
  "Milvus": "database",
  "MongoDB": "database",
  "Mongoose": "database",
  "MySQL": "database",
  "Neo4j": "database",
  "Neon": "database",
  "OpenSearch": "database",
  "Oracle Database": "database",
  "pgvector": "database",
  "Pinecone": "database",
  "PlanetScale": "database",
  "PostgreSQL": "database",
  "Prisma": "database",
  "Qdrant": "database",
  "QuestDB": "database",
  "Redis": "database",
  "RethinkDB": "database",
  "RocksDB": "database",
  "rqlite": "database",
  "ScyllaDB": "database",
  "Sequelize": "database",
  "SingleStore": "database",
  "SQLAlchemy": "database",
  "SQLite": "database",
  "Supabase": "database",
  "Supabase Storage": "database",
  "SurrealDB": "database",
  "TiDB": "database",
  "TimescaleDB": "database",
  "Turso": "database",
  "TypeORM": "database",
  "Typesense": "database",
  "Vald": "database",
  "Vectara": "database",
  "Vespa": "database",
  "Vitess": "database",
  "Weaviate": "database",
  "YugabyteDB": "database",

  // ==========================================================================
  // DEVOPS
  // ==========================================================================
  "Amazon CloudWatch": "devops",
  "Ansible": "devops",
  "Apache Airflow": "devops",
  "Apache Ant": "devops",
  "Apache Flink": "devops",
  "Apache Hadoop": "devops",
  "Apache Hive": "devops",
  "Apache HTTP Server": "devops",
  "Apache NiFi": "devops",
  "Apache Pig": "devops",
  "Apache Spark": "devops",
  "Apache Storm": "devops",
  "AppDynamics": "devops",
  "Argo CD": "devops",
  "Argo Events": "devops",
  "Argo Rollouts": "devops",
  "Argo Workflows": "devops",
  "AWS CDK": "devops",
  "AWS CloudFormation": "devops",
  "AWS Copilot": "devops",
  "AWS SAM": "devops",
  "Azure DevOps": "devops",
  "Babel": "devops",
  "Bamboo": "devops",
  "Bazel": "devops",
  "Bugsnag": "devops",
  "Caddy": "devops",
  "cert-manager": "devops",
  "Checkly": "devops",
  "Chef": "devops",
  "CI/CD": "devops",
  "CircleCI": "devops",
  "containerd": "devops",
  "Continuous Deployment": "devops",
  "Continuous Integration": "devops",
  "Crossplane": "devops",
  "Datadog": "devops",
  "dbt": "devops",
  "DevOps": "devops",
  "Docker": "devops",
  "Docker Compose": "devops",
  "Dockerfile": "devops",
  "Dynatrace": "devops",
  "EFK Stack": "devops",
  "ELK Stack": "devops",
  "Envoy": "devops",
  "esbuild": "devops",
  "etcd": "devops",
  "External Secrets Operator": "devops",
  "Flagger": "devops",
  "Fluent Bit": "devops",
  "Fluentd": "devops",
  "Flux CD": "devops",
  "GitHub Actions": "devops",
  "GitLab CI/CD": "devops",
  "GitOps": "devops",
  "Gradle": "devops",
  "Grafana": "devops",
  "Grafana Alloy": "devops",
  "Grafana Loki": "devops",
  "Grafana Mimir": "devops",
  "Grafana OnCall": "devops",
  "Grafana Tempo": "devops",
  "Grunt": "devops",
  "Gulp": "devops",
  "HAProxy": "devops",
  "HashiCorp": "devops",
  "HashiCorp Consul": "devops",
  "HashiCorp Nomad": "devops",
  "HashiCorp Vault": "devops",
  "HDFS": "devops",
  "Helm": "devops",
  "Highlight": "devops",
  "Honeycomb": "devops",
  "Internet Information Services": "devops",
  "Istio": "devops",
  "Jaeger": "devops",
  "Jenkins": "devops",
  "Karpenter": "devops",
  "Kibana": "devops",
  "Kong Gateway": "devops",
  "Kubernetes": "devops",
  "Kustomize": "devops",
  "Let's Encrypt": "devops",
  "Lightstep": "devops",
  "LogRocket": "devops",
  "Logstash": "devops",
  "Luigi": "devops",
  "Make": "devops",
  "Makefile": "devops",
  "Maven": "devops",
  "MSBuild": "devops",
  "Nagios": "devops",
  "New Relic": "devops",
  "Nginx": "devops",
  "Nx": "devops",
  "OpenShift": "devops",
  "OpenTelemetry": "devops",
  "OpenTelemetry Collector": "devops",
  "Packer": "devops",
  "PagerDuty": "devops",
  "Parcel": "devops",
  "PM2": "devops",
  "Podman": "devops",
  "Presto": "devops",
  "Prometheus": "devops",
  "Pulumi": "devops",
  "Puppet": "devops",
  "PySpark": "devops",
  "Rancher": "devops",
  "Rollbar": "devops",
  "Rollup": "devops",
  "Sealed Secrets": "devops",
  "Sentry": "devops",
  "Serverless Framework": "devops",
  "SigNoz": "devops",
  "Snyk": "devops",
  "SonarCloud": "devops",
  "SonarQube": "devops",
  "Spark Streaming": "devops",
  "Spinnaker": "devops",
  "Splunk": "devops",
  "SST": "devops",
  "SWC": "devops",
  "TeamCity": "devops",
  "Terraform": "devops",
  "Traefik": "devops",
  "Travis CI": "devops",
  "Trino": "devops",
  "Turbopack": "devops",
  "Turborepo": "devops",
  "Uptime Kuma": "devops",
  "Vagrant": "devops",
  "Varnish": "devops",
  "Vector": "devops",
  "Veracode": "devops",
  "Vite": "devops",
  "Webpack": "devops",
  "Zabbix": "devops",
  "Zipkin": "devops",

  // ==========================================================================
  // CLOUD
  // ==========================================================================
  "Alibaba Cloud": "cloud",
  "Amazon API Gateway": "cloud",
  "Amazon CloudFront": "cloud",
  "Amazon Cognito": "cloud",
  "Amazon EC2": "cloud",
  "Amazon ECR": "cloud",
  "Amazon ECS": "cloud",
  "Amazon EKS": "cloud",
  "Amazon EventBridge": "cloud",
  "Amazon Route 53": "cloud",
  "Amazon S3": "cloud",
  "Amazon SNS": "cloud",
  "Amazon SQS": "cloud",
  "Amazon Web Services": "cloud",
  "Apigee": "cloud",
  "AWS Amplify": "cloud",
  "AWS Elastic Beanstalk": "cloud",
  "AWS Fargate": "cloud",
  "AWS IAM": "cloud",
  "AWS Lambda": "cloud",
  "AWS Step Functions": "cloud",
  "Azure App Service": "cloud",
  "Azure Blob Storage": "cloud",
  "Azure Event Hubs": "cloud",
  "Azure Functions": "cloud",
  "Azure Kubernetes Service": "cloud",
  "Azure Logic Apps": "cloud",
  "Azure Service Bus": "cloud",
  "Cloudflare": "cloud",
  "Cloudflare Access": "cloud",
  "Cloudflare Durable Objects": "cloud",
  "Cloudflare Pages": "cloud",
  "Cloudflare R2": "cloud",
  "Cloudflare Tunnel": "cloud",
  "Cloudflare Workers": "cloud",
  "Cloudflare Zero Trust": "cloud",
  "Databricks": "cloud",
  "DigitalOcean": "cloud",
  "Edge Functions": "cloud",
  "Fly.io": "cloud",
  "Google App Engine": "cloud",
  "Google Cloud Functions": "cloud",
  "Google Cloud Platform": "cloud",
  "Google Cloud Pub/Sub": "cloud",
  "Google Cloud Run": "cloud",
  "Google Cloud Storage": "cloud",
  "Google Compute Engine": "cloud",
  "Google Kubernetes Engine": "cloud",
  "Heroku": "cloud",
  "IBM Cloud": "cloud",
  "Linode": "cloud",
  "Microsoft Azure": "cloud",
  "Netlify": "cloud",
  "Oracle Cloud Infrastructure": "cloud",
  "Railway": "cloud",
  "Render": "cloud",
  "Snowflake": "cloud",
  "Vercel": "cloud",
  "Virtual Private Cloud": "cloud",
  "Vultr": "cloud",

  // ==========================================================================
  // AI
  // ==========================================================================
  "Agentic AI": "ai",
  "AI Agents": "ai",
  "Amazon Bedrock": "ai",
  "Amazon SageMaker": "ai",
  "Anthropic": "ai",
  "AnythingLLM": "ai",
  "Artificial Intelligence": "ai",
  "AutoGen": "ai",
  "Azure OpenAI": "ai",
  "Caffe": "ai",
  "CatBoost": "ai",
  "ChatGPT": "ai",
  "Claude": "ai",
  "Codeium": "ai",
  "Cohere": "ai",
  "Computer Vision": "ai",
  "Continue": "ai",
  "CrewAI": "ai",
  "DALL-E": "ai",
  "Deep Learning": "ai",
  "DeepSeek": "ai",
  "DSPy": "ai",
  "ElevenLabs": "ai",
  "Embeddings": "ai",
  "FAISS": "ai",
  "Falcon": "ai",
  "Fine-Tuning": "ai",
  "Flowise": "ai",
  "Generative AI": "ai",
  "Gensim": "ai",
  "GGML": "ai",
  "GGUF": "ai",
  "GitHub Copilot": "ai",
  "Google Gemini": "ai",
  "Google Vertex AI": "ai",
  "GPT": "ai",
  "GPT-4": "ai",
  "Grok": "ai",
  "Haystack": "ai",
  "Hugging Face": "ai",
  "Hugging Face Transformers": "ai",
  "JAX": "ai",
  "Keras": "ai",
  "Knowledge Graph": "ai",
  "Kubeflow": "ai",
  "LangChain": "ai",
  "Langfuse": "ai",
  "LangGraph": "ai",
  "LangSmith": "ai",
  "Large Language Model": "ai",
  "Large Language Models": "ai",
  "LightGBM": "ai",
  "LiteLLM": "ai",
  "Llama": "ai",
  "llama.cpp": "ai",
  "LlamaIndex": "ai",
  "LM Studio": "ai",
  "Machine Learning": "ai",
  "Midjourney": "ai",
  "Mistral": "ai",
  "Mixtral": "ai",
  "MLflow": "ai",
  "Model Context Protocol": "ai",
  "Multi-Agent Systems": "ai",
  "Natural Language Processing": "ai",
  "NLTK": "ai",
  "NumPy": "ai",
  "Ollama": "ai",
  "ONNX": "ai",
  "Open WebUI": "ai",
  "OpenAI": "ai",
  "OpenAI API": "ai",
  "OpenAI Whisper": "ai",
  "OpenCV": "ai",
  "OpenRouter": "ai",
  "pandas": "ai",
  "Perplexity AI": "ai",
  "Phi": "ai",
  "Prompt Engineering": "ai",
  "PyTorch": "ai",
  "Qwen": "ai",
  "Retrieval-Augmented Generation": "ai",
  "RunwayML": "ai",
  "scikit-learn": "ai",
  "SciPy": "ai",
  "Semantic Kernel": "ai",
  "Semantic Search": "ai",
  "spaCy": "ai",
  "Stability AI": "ai",
  "Stable Diffusion": "ai",
  "Tabnine": "ai",
  "TensorFlow": "ai",
  "Text Generation WebUI": "ai",
  "Theano": "ai",
  "Vector Embeddings": "ai",
  "Vector Search": "ai",
  "vLLM": "ai",
  "Windsurf": "ai",
  "XGBoost": "ai",
  "YOLO": "ai",

  // ==========================================================================
  // TESTING
  // ==========================================================================
  "Allure Report": "testing",
  "Appium": "testing",
  "Chai": "testing",
  "Chromatic": "testing",
  "Codecov": "testing",
  "Coveralls": "testing",
  "Cucumber": "testing",
  "Cypress": "testing",
  "Detox": "testing",
  "Enzyme": "testing",
  "Gatling": "testing",
  "Insomnia": "testing",
  "Jasmine": "testing",
  "Jest": "testing",
  "JMeter": "testing",
  "JUnit": "testing",
  "k6": "testing",
  "Mocha": "testing",
  "PHPUnit": "testing",
  "Playwright": "testing",
  "Postman": "testing",
  "Puppeteer": "testing",
  "pytest": "testing",
  "React Testing Library": "testing",
  "Robot Framework": "testing",
  "RSpec": "testing",
  "Selenium": "testing",
  "TestCafe": "testing",
  "Testing Library": "testing",
  "TestNG": "testing",
  "unittest": "testing",
  "Vitest": "testing",
  "WebdriverIO": "testing",

  // ==========================================================================
  // TOOLS
  // ==========================================================================
  "1Password": "tools",
  "Adobe Illustrator": "tools",
  "Adobe Photoshop": "tools",
  "Adobe XD": "tools",
  "Airtable": "tools",
  "Amplitude": "tools",
  "Android Studio": "tools",
  "Apache Superset": "tools",
  "AppSheet": "tools",
  "Appsmith": "tools",
  "APT": "tools",
  "Asana": "tools",
  "asdf": "tools",
  "Atom": "tools",
  "Azure Repos": "tools",
  "Basecamp": "tools",
  "Biome": "tools",
  "Bitbucket": "tools",
  "Bitwarden": "tools",
  "Bubble": "tools",
  "Budibase": "tools",
  "Builder.io": "tools",
  "Burp Suite": "tools",
  "Canva": "tools",
  "Cargo": "tools",
  "Changesets": "tools",
  "Claude Code": "tools",
  "Claude Desktop": "tools",
  "ClickUp": "tools",
  "Cloudinary": "tools",
  "commitlint": "tools",
  "Composer": "tools",
  "Conda": "tools",
  "Confluence": "tools",
  "Corepack": "tools",
  "Cursor": "tools",
  "Docker Desktop": "tools",
  "Docusaurus": "tools",
  "Eclipse": "tools",
  "Emacs": "tools",
  "ESLint": "tools",
  "FigJam": "tools",
  "Figma": "tools",
  "Framer": "tools",
  "FullStory": "tools",
  "Git": "tools",
  "GitBook": "tools",
  "GitHub": "tools",
  "GitLab": "tools",
  "Glide": "tools",
  "Google Analytics": "tools",
  "Homebrew": "tools",
  "Hotjar": "tools",
  "Husky": "tools",
  "IFTTT": "tools",
  "Imgix": "tools",
  "IntelliJ IDEA": "tools",
  "InVision": "tools",
  "Jira": "tools",
  "JSDoc": "tools",
  "LaunchDarkly": "tools",
  "Lerna": "tools",
  "Linear": "tools",
  "lint-staged": "tools",
  "Looker": "tools",
  "Mailgun": "tools",
  "Mendix": "tools",
  "Mercurial": "tools",
  "Metabase": "tools",
  "Metasploit": "tools",
  "Microsoft Teams": "tools",
  "Miro": "tools",
  "Mixpanel": "tools",
  "Monday.com": "tools",
  "n8n": "tools",
  "Neovim": "tools",
  "NetBeans": "tools",
  "Nmap": "tools",
  "Notion": "tools",
  "npm": "tools",
  "npm Workspaces": "tools",
  "npx": "tools",
  "NuGet": "tools",
  "nvm": "tools",
  "OutSystems": "tools",
  "Penpot": "tools",
  "Perforce": "tools",
  "pip": "tools",
  "PlatformIO": "tools",
  "pnpm": "tools",
  "pnpm Workspaces": "tools",
  "PostHog": "tools",
  "Postmark": "tools",
  "Power Apps": "tools",
  "Power Automate": "tools",
  "Power BI": "tools",
  "Prettier": "tools",
  "Productboard": "tools",
  "PyCharm": "tools",
  "Resend": "tools",
  "Retool": "tools",
  "RubyGems": "tools",
  "Segment": "tools",
  "semantic-release": "tools",
  "SendGrid": "tools",
  "Sketch": "tools",
  "Slack": "tools",
  "Softr": "tools",
  "Statuspage": "tools",
  "Storybook": "tools",
  "Stylelint": "tools",
  "Sublime Text": "tools",
  "Subversion": "tools",
  "Tableau": "tools",
  "Trello": "tools",
  "TSLint": "tools",
  "Twilio": "tools",
  "UploadThing": "tools",
  "Vim": "tools",
  "Visual Studio": "tools",
  "Visual Studio Code": "tools",
  "Volta": "tools",
  "Webflow": "tools",
  "WebStorm": "tools",
  "Wireshark": "tools",
  "Workato": "tools",
  "Xcode": "tools",
  "Yarn": "tools",
  "Yarn Workspaces": "tools",
  "YUM": "tools",
  "Zapier": "tools",
  "Zeplin": "tools",

  // ==========================================================================
  // MOBILE
  // ==========================================================================
  "Android": "mobile",
  "Apache Cordova": "mobile",
  "ARCore": "mobile",
  "ARKit": "mobile",
  "Capacitor": "mobile",
  "Expo": "mobile",
  "Expo Go": "mobile",
  "Expo Router": "mobile",
  "Flipper": "mobile",
  "Flutter": "mobile",
  "Ionic": "mobile",
  "iOS": "mobile",
  "Jetpack Compose": "mobile",
  "NativeWind": "mobile",
  "React Native": "mobile",
  "React Native CLI": "mobile",
  "React Native Paper": "mobile",
  "React Navigation": "mobile",
  "SwiftUI": "mobile",
  "UIKit": "mobile",
  "Xamarin": "mobile",

  // ==========================================================================
  // OPERATING SYSTEMS
  // ==========================================================================
  "Arch Linux": "operatingSystems",
  "CentOS": "operatingSystems",
  "Debian": "operatingSystems",
  "Fedora": "operatingSystems",
  "FreeBSD": "operatingSystems",
  "Kali Linux": "operatingSystems",
  "Linux": "operatingSystems",
  "macOS": "operatingSystems",
  "Red Hat Enterprise Linux": "operatingSystems",
  "Solaris": "operatingSystems",
  "Ubuntu": "operatingSystems",
  "Unix": "operatingSystems",
  "Windows": "operatingSystems",
  "Windows Server": "operatingSystems",

  // ==========================================================================
  // MISCELLANEOUS
  // ==========================================================================
  "Agile": "miscellaneous",
  "Alchemy": "miscellaneous",
  "Anchor": "miscellaneous",
  "API Gateway": "miscellaneous",
  "Arduino": "miscellaneous",
  "ArduPilot": "miscellaneous",
  "Augmented Reality": "miscellaneous",
  "Behavior-Driven Development": "miscellaneous",
  "BigCommerce": "miscellaneous",
  "Bitcoin": "miscellaneous",
  "Blockchain": "miscellaneous",
  "Bluetooth Low Energy": "miscellaneous",
  "CAN Bus": "miscellaneous",
  "Chainlink": "miscellaneous",
  "CISA": "miscellaneous",
  "Clean Architecture": "miscellaneous",
  "Cocos2d": "miscellaneous",
  "CommonJS": "miscellaneous",
  "Content Delivery Network": "miscellaneous",
  "Contentful": "miscellaneous",
  "CORS": "miscellaneous",
  "CQRS": "miscellaneous",
  "CryEngine": "miscellaneous",
  "CSRF": "miscellaneous",
  "Cybersecurity": "miscellaneous",
  "DAO": "miscellaneous",
  "DeFi": "miscellaneous",
  "Design Patterns": "miscellaneous",
  "DirectX": "miscellaneous",
  "DNS": "miscellaneous",
  "Domain-Driven Design": "miscellaneous",
  "Drupal": "miscellaneous",
  "ECMAScript Modules": "miscellaneous",
  "Edge Computing": "miscellaneous",
  "Electron": "miscellaneous",
  "Embedded Systems": "miscellaneous",
  "ERC-20": "miscellaneous",
  "ERC-721": "miscellaneous",
  "ESP32": "miscellaneous",
  "ESP8266": "miscellaneous",
  "Ethereum": "miscellaneous",
  "Ethers.js": "miscellaneous",
  "Ethical Hacking": "miscellaneous",
  "Event-Driven Architecture": "miscellaneous",
  "Feature Flags": "miscellaneous",
  "Firewall": "miscellaneous",
  "Foundry": "miscellaneous",
  "FreeRTOS": "miscellaneous",
  "Gazebo": "miscellaneous",
  "GDPR": "miscellaneous",
  "Ghost": "miscellaneous",
  "Godot": "miscellaneous",
  "GTK": "miscellaneous",
  "Hardhat": "miscellaneous",
  "Headless CMS": "miscellaneous",
  "HIPAA": "miscellaneous",
  "HTTP": "miscellaneous",
  "HTTPS": "miscellaneous",
  "Hydration": "miscellaneous",
  "Hygraph": "miscellaneous",
  "Hyperledger": "miscellaneous",
  "Incremental Static Regeneration": "miscellaneous",
  "Information Security": "miscellaneous",
  "Infura": "miscellaneous",
  "Internet of Things": "miscellaneous",
  "IPFS": "miscellaneous",
  "Islands Architecture": "miscellaneous",
  "ISO 27001": "miscellaneous",
  "Jamstack": "miscellaneous",
  "JavaFX": "miscellaneous",
  "Joomla": "miscellaneous",
  "Kanban": "miscellaneous",
  "KeystoneJS": "miscellaneous",
  "Layer 2": "miscellaneous",
  "Load Balancing": "miscellaneous",
  "LoRa": "miscellaneous",
  "LoRaWAN": "miscellaneous",
  "Magento": "miscellaneous",
  "MetaMask": "miscellaneous",
  "Micro Frontends": "miscellaneous",
  "Microservices": "miscellaneous",
  "Mixed Reality": "miscellaneous",
  "Modbus": "miscellaneous",
  "Module Federation": "miscellaneous",
  "Monolithic Architecture": "miscellaneous",
  "Monorepo": "miscellaneous",
  "MQTT": "miscellaneous",
  "MVC": "miscellaneous",
  "MVVM": "miscellaneous",
  "NFT": "miscellaneous",
  "Oculus SDK": "miscellaneous",
  "OpenGL": "miscellaneous",
  "OpenVPN": "miscellaneous",
  "OpenZeppelin": "miscellaneous",
  "OWASP": "miscellaneous",
  "Payload CMS": "miscellaneous",
  "PayPal": "miscellaneous",
  "PCI DSS": "miscellaneous",
  "Penetration Testing": "miscellaneous",
  "Phaser": "miscellaneous",
  "PLC": "miscellaneous",
  "Polygon": "miscellaneous",
  "PrestaShop": "miscellaneous",
  "Prismic": "miscellaneous",
  "Progressive Web App": "miscellaneous",
  "PX4": "miscellaneous",
  "Qt": "miscellaneous",
  "RainbowKit": "miscellaneous",
  "Raspberry Pi": "miscellaneous",
  "Rate Limiting": "miscellaneous",
  "Razorpay": "miscellaneous",
  "Reverse Proxy": "miscellaneous",
  "Robot Operating System": "miscellaneous",
  "Robotics": "miscellaneous",
  "ROS 2": "miscellaneous",
  "RTOS": "miscellaneous",
  "Sanity": "miscellaneous",
  "SCADA": "miscellaneous",
  "Scrum": "miscellaneous",
  "Server-Side Rendering": "miscellaneous",
  "Serverless": "miscellaneous",
  "Service Mesh": "miscellaneous",
  "Shopify": "miscellaneous",
  "SIEM": "miscellaneous",
  "Single Page Application": "miscellaneous",
  "Site Reliability Engineering": "miscellaneous",
  "Smart Contracts": "miscellaneous",
  "SOC 2": "miscellaneous",
  "Solana": "miscellaneous",
  "SOLID Principles": "miscellaneous",
  "SQL Injection": "miscellaneous",
  "SSH": "miscellaneous",
  "SSL": "miscellaneous",
  "Static Site Generation": "miscellaneous",
  "STM32": "miscellaneous",
  "Storyblok": "miscellaneous",
  "Strapi": "miscellaneous",
  "Stripe": "miscellaneous",
  "Tauri": "miscellaneous",
  "TCP/IP": "miscellaneous",
  "Test-Driven Development": "miscellaneous",
  "The Graph": "miscellaneous",
  "TLS": "miscellaneous",
  "Truffle": "miscellaneous",
  "Unity": "miscellaneous",
  "Unreal Engine": "miscellaneous",
  "Virtual Reality": "miscellaneous",
  "VPN": "miscellaneous",
  "Vulkan": "miscellaneous",
  "wagmi": "miscellaneous",
  "WalletConnect": "miscellaneous",
  "Waterfall": "miscellaneous",
  "Web Application Firewall": "miscellaneous",
  "Web3": "miscellaneous",
  "Web3.js": "miscellaneous",
  "WebAssembly": "miscellaneous",
  "WebXR": "miscellaneous",
  "Windows Forms": "miscellaneous",
  "WireGuard": "miscellaneous",
  "WooCommerce": "miscellaneous",
  "WordPress": "miscellaneous",
  "WPF": "miscellaneous",
  "XSS": "miscellaneous",
  "Zero Trust": "miscellaneous",
  "Zero-Knowledge Proofs": "miscellaneous",
  "Zigbee": "miscellaneous",
  "ZK-Rollups": "miscellaneous",
} as const;

export type SkillCategory =
  | "ai"
  | "cloud"
  | "tools"
  | "devops"
  | "mobile"
  | "backend"
  | "testing"
  | "database"
  | "frontend"
  | "languages"
  | "softSkills"
  | "miscellaneous"
  | "operatingSystems";

export type TechnologyCategoryKey = keyof typeof TECHNOLOGY_CATEGORIES;

export type TechnologyCategory =
  (typeof TECHNOLOGY_CATEGORIES)[keyof typeof TECHNOLOGY_CATEGORIES];