// ============================================================================
// TECHNOLOGY_ALIASES
// Production-grade technology alias knowledge base for resume normalization,
// ATS parsing, AI extraction, and job matching.
//
// RULES:
// - Keys are normalized lookup strings: lowercase, trimmed, single spaces.
// - Values are canonical display names.
// - No functions, no regex, no fuzzy matching — static mapping only.
// - Consumed by technology.utils.ts
// ============================================================================

export const TECHNOLOGY_ALIASES = {
  // ==========================================================================
  // PROGRAMMING LANGUAGES
  // ==========================================================================
  "c": "C",
  "c#": "C#",
  "c sharp": "C#",
  "csharp": "C#",
  "c++": "C++",
  "cpp": "C++",
  "c plus plus": "C++",
  "clojure": "Clojure",
  "cobol": "COBOL",
  "coffeescript": "CoffeeScript",
  "crystal": "Crystal",
  "dart": "Dart",
  "delphi": "Delphi",
  "elixir": "Elixir",
  "elm": "Elm",
  "erlang": "Erlang",
  "f#": "F#",
  "fsharp": "F#",
  "fortran": "Fortran",
  "go": "Go",
  "golang": "Go",
  "groovy": "Groovy",
  "haskell": "Haskell",
  "java": "Java",
  "javascript": "JavaScript",
  "js": "JavaScript",
  "julia": "Julia",
  "kotlin": "Kotlin",
  "lisp": "Lisp",
  "lua": "Lua",
  "matlab": "MATLAB",
  "objective c": "Objective-C",
  "objective-c": "Objective-C",
  "objectivec": "Objective-C",
  "ocaml": "OCaml",
  "pascal": "Pascal",
  "perl": "Perl",
  "php": "PHP",
  "powershell": "PowerShell",
  "prolog": "Prolog",
  "python": "Python",
  "python3": "Python",
  "python 3": "Python",
  "r": "R",
  "r lang": "R",
  "ruby": "Ruby",
  "rust": "Rust",
  "sas": "SAS",
  "scala": "Scala",
  "scheme": "Scheme",
  "shell": "Shell Scripting",
  "shell scripting": "Shell Scripting",
  "bash": "Bash",
  "bash scripting": "Bash",
  "zsh": "Zsh",
  "solidity": "Solidity",
  "sql": "SQL",
  "swift": "Swift",
  "typescript": "TypeScript",
  "ts": "TypeScript",
  "vb.net": "VB.NET",
  "vbnet": "VB.NET",
  "visual basic": "Visual Basic",
  "visual basic .net": "VB.NET",
  "vba": "VBA",
  "zig": "Zig",
  "nim": "Nim",
  "assembly": "Assembly",
  "asm": "Assembly",
  "haxe": "Haxe",
  "abap": "ABAP",

  // ==========================================================================
  // FRONTEND FRAMEWORKS / LIBRARIES
  // ==========================================================================
  "react": "React.js",
  "reactjs": "React.js",
  "react.js": "React.js",
  "react js": "React.js",
  "next": "Next.js",
  "nextjs": "Next.js",
  "next.js": "Next.js",
  "next js": "Next.js",
  "vue": "Vue.js",
  "vuejs": "Vue.js",
  "vue.js": "Vue.js",
  "vue js": "Vue.js",
  "vue3": "Vue.js",
  "nuxt": "Nuxt.js",
  "nuxtjs": "Nuxt.js",
  "nuxt.js": "Nuxt.js",
  "nuxt js": "Nuxt.js",
  "angular": "Angular",
  "angularjs": "AngularJS",
  "angular js": "AngularJS",
  "angular 2+": "Angular",
  "svelte": "Svelte",
  "sveltekit": "SvelteKit",
  "svelte kit": "SvelteKit",
  "solidjs": "SolidJS",
  "solid.js": "SolidJS",
  "solid js": "SolidJS",
  "qwik": "Qwik",
  "astro": "Astro",
  "astrojs": "Astro",
  "ember": "Ember.js",
  "emberjs": "Ember.js",
  "ember.js": "Ember.js",
  "backbone": "Backbone.js",
  "backbonejs": "Backbone.js",
  "backbone.js": "Backbone.js",
  "jquery": "jQuery",
  "htmx": "htmx",
  "alpine": "Alpine.js",
  "alpinejs": "Alpine.js",
  "alpine.js": "Alpine.js",
  "remix": "Remix",
  "remix.run": "Remix",
  "gatsby": "Gatsby",
  "gatsbyjs": "Gatsby",
  "gatsby.js": "Gatsby",
  "preact": "Preact",
  "lit": "Lit",
  "lit element": "Lit",
  "litelement": "Lit",
  "webcomponents": "Web Components",
  "web components": "Web Components",
  "html": "HTML",
  "html5": "HTML5",
  "css": "CSS",
  "css3": "CSS3",
  "sass": "Sass",
  "scss": "Sass",
  "less": "Less",
  "stylus": "Stylus",
  "postcss": "PostCSS",

  // ==========================================================================
  // UI LIBRARIES / DESIGN SYSTEMS
  // ==========================================================================
  "tailwind": "Tailwind CSS",
  "tailwindcss": "Tailwind CSS",
  "tailwind css": "Tailwind CSS",
  "bootstrap": "Bootstrap",
  "bootstrap5": "Bootstrap",
  "bulma": "Bulma",
  "material ui": "Material UI",
  "materialui": "Material UI",
  "mui": "Material UI",
  "material design": "Material Design",
  "ant design": "Ant Design",
  "antd": "Ant Design",
  "chakra ui": "Chakra UI",
  "chakraui": "Chakra UI",
  "shadcn": "shadcn/ui",
  "shadcn ui": "shadcn/ui",
  "shadcn/ui": "shadcn/ui",
  "radix": "Radix UI",
  "radix ui": "Radix UI",
  "headless ui": "Headless UI",
  "headlessui": "Headless UI",
  "semantic ui": "Semantic UI",
  "primereact": "PrimeReact",
  "primeng": "PrimeNG",
  "vuetify": "Vuetify",
  "quasar": "Quasar",
  "foundation": "Foundation",
  "framer motion": "Framer Motion",
  "framer-motion": "Framer Motion",
  "gsap": "GSAP",
  "three.js": "Three.js",
  "threejs": "Three.js",
  "three js": "Three.js",
  "d3": "D3.js",
  "d3.js": "D3.js",
  "d3js": "D3.js",
  "chart.js": "Chart.js",
  "chartjs": "Chart.js",
  "recharts": "Recharts",
  "highcharts": "Highcharts",

  // ==========================================================================
  // STATE MANAGEMENT
  // ==========================================================================
  "redux": "Redux",
  "redux toolkit": "Redux Toolkit",
  "rtk": "Redux Toolkit",
  "zustand": "Zustand",
  "recoil": "Recoil",
  "jotai": "Jotai",
  "mobx": "MobX",
  "xstate": "XState",
  "vuex": "Vuex",
  "pinia": "Pinia",
  "ngrx": "NgRx",
  "context api": "React Context API",
  "react context": "React Context API",
  "tanstack query": "TanStack Query",
  "react query": "TanStack Query",
  "swr": "SWR",
  "apollo client": "Apollo Client",

  // ==========================================================================
  // FORMS / VALIDATION
  // ==========================================================================
  "react hook form": "React Hook Form",
  "formik": "Formik",
  "zod": "Zod",
  "yup": "Yup",
  "joi": "Joi",
  "ajv": "Ajv",

  // ==========================================================================
  // BACKEND FRAMEWORKS
  // ==========================================================================
  "node": "Node.js",
  "nodejs": "Node.js",
  "node.js": "Node.js",
  "node js": "Node.js",
  "express": "Express.js",
  "expressjs": "Express.js",
  "express.js": "Express.js",
  "express js": "Express.js",
  "nest": "NestJS",
  "nestjs": "NestJS",
  "nest.js": "NestJS",
  "nest js": "NestJS",
  "koa": "Koa.js",
  "koajs": "Koa.js",
  "koa.js": "Koa.js",
  "hapi": "Hapi.js",
  "hapijs": "Hapi.js",
  "fastify": "Fastify",
  "adonis": "AdonisJS",
  "adonisjs": "AdonisJS",
  "django": "Django",
  "django rest framework": "Django REST Framework",
  "drf": "Django REST Framework",
  "flask": "Flask",
  "fastapi": "FastAPI",
  "tornado": "Tornado",
  "pyramid": "Pyramid",
  "rails": "Ruby on Rails",
  "ruby on rails": "Ruby on Rails",
  "ror": "Ruby on Rails",
  "sinatra": "Sinatra",
  "laravel": "Laravel",
  "symfony": "Symfony",
  "codeigniter": "CodeIgniter",
  "yii": "Yii",
  "spring": "Spring Framework",
  "spring boot": "Spring Boot",
  "springboot": "Spring Boot",
  "spring mvc": "Spring MVC",
  "quarkus": "Quarkus",
  "micronaut": "Micronaut",
  "asp.net": "ASP.NET",
  "aspnet": "ASP.NET",
  "asp.net core": "ASP.NET Core",
  "aspnet core": "ASP.NET Core",
  ".net": ".NET",
  "dotnet": ".NET",
  ".net core": ".NET Core",
  "dotnet core": ".NET Core",
  ".net framework": ".NET Framework",
  "gin": "Gin",
  "echo": "Echo",
  "fiber": "Fiber",
  "beego": "Beego",
  "actix": "Actix",
  "actix web": "Actix Web",
  "rocket": "Rocket",
  "phoenix": "Phoenix Framework",
  "phoenix framework": "Phoenix Framework",

  // ==========================================================================
  // API TECHNOLOGIES
  // ==========================================================================
  "rest": "REST API",
  "rest api": "REST API",
  "restful": "REST API",
  "restful api": "REST API",
  "graphql": "GraphQL",
  "grpc": "gRPC",
  "soap": "SOAP",
  "openapi": "OpenAPI",
  "swagger": "Swagger",
  "websocket": "WebSocket",
  "websockets": "WebSocket",
  "socket.io": "Socket.IO",
  "socketio": "Socket.IO",
  "socket io": "Socket.IO",
  "webrtc": "WebRTC",
  "trpc": "tRPC",
  "json rpc": "JSON-RPC",
  "jsonrpc": "JSON-RPC",
  "sse": "Server-Sent Events",
  "server sent events": "Server-Sent Events",

  // ==========================================================================
  // AUTHENTICATION / IDENTITY
  // ==========================================================================
  "oauth": "OAuth 2.0",
  "oauth2": "OAuth 2.0",
  "oauth 2.0": "OAuth 2.0",
  "openid connect": "OpenID Connect",
  "oidc": "OpenID Connect",
  "jwt": "JWT",
  "json web token": "JWT",
  "saml": "SAML",
  "clerk": "Clerk",
  "auth0": "Auth0",
  "keycloak": "Keycloak",
  "okta": "Okta",
  "firebase auth": "Firebase Authentication",
  "firebase authentication": "Firebase Authentication",
  "next-auth": "NextAuth.js",
  "nextauth": "NextAuth.js",
  "nextauth.js": "NextAuth.js",
  "passport": "Passport.js",
  "passportjs": "Passport.js",
  "passport.js": "Passport.js",
  "supertokens": "SuperTokens",
  "ldap": "LDAP",
  "active directory": "Active Directory",
  "ping identity": "Ping Identity",
  "azure ad": "Azure Active Directory",
  "azure active directory": "Azure Active Directory",
  "cognito": "Amazon Cognito",
  "amazon cognito": "Amazon Cognito",

  // ==========================================================================
  // DATABASES (RELATIONAL)
  // ==========================================================================
  "postgres": "PostgreSQL",
  "postgresql": "PostgreSQL",
  "postgre": "PostgreSQL",
  "pgsql": "PostgreSQL",
  "mysql": "MySQL",
  "mariadb": "MariaDB",
  "sqlite": "SQLite",
  "sqlite3": "SQLite",
  "ms sql": "Microsoft SQL Server",
  "mssql": "Microsoft SQL Server",
  "sql server": "Microsoft SQL Server",
  "microsoft sql server": "Microsoft SQL Server",
  "oracle": "Oracle Database",
  "oracle db": "Oracle Database",
  "oracle database": "Oracle Database",
  "db2": "IBM Db2",
  "ibm db2": "IBM Db2",
  "cockroachdb": "CockroachDB",
  "cockroach db": "CockroachDB",
  "planetscale": "PlanetScale",
  "aurora": "Amazon Aurora",
  "amazon aurora": "Amazon Aurora",

  // ==========================================================================
  // DATABASES (NOSQL / DOCUMENT / KEY-VALUE)
  // ==========================================================================
  "mongo": "MongoDB",
  "mongodb": "MongoDB",
  "mongo db": "MongoDB",
  "couchdb": "CouchDB",
  "couchbase": "Couchbase",
  "dynamodb": "Amazon DynamoDB",
  "dynamo db": "Amazon DynamoDB",
  "amazon dynamodb": "Amazon DynamoDB",
  "cosmos db": "Azure Cosmos DB",
  "cosmosdb": "Azure Cosmos DB",
  "azure cosmos db": "Azure Cosmos DB",
  "redis": "Redis",
  "memcached": "Memcached",
  "cassandra": "Apache Cassandra",
  "apache cassandra": "Apache Cassandra",
  "scylladb": "ScyllaDB",
  "hbase": "Apache HBase",
  "firestore": "Cloud Firestore",
  "cloud firestore": "Cloud Firestore",
  "firebase realtime database": "Firebase Realtime Database",
  "realtime database": "Firebase Realtime Database",
  "supabase": "Supabase",
  "etcd": "etcd",

  // ==========================================================================
  // GRAPH DATABASES
  // ==========================================================================
  "neo4j": "Neo4j",
  "arangodb": "ArangoDB",
  "dgraph": "Dgraph",
  "amazon neptune": "Amazon Neptune",
  "neptune": "Amazon Neptune",

  // ==========================================================================
  // VECTOR DATABASES
  // ==========================================================================
  "pinecone": "Pinecone",
  "weaviate": "Weaviate",
  "milvus": "Milvus",
  "qdrant": "Qdrant",
  "chroma": "Chroma",
  "chromadb": "Chroma",
  "faiss": "FAISS",
  "pgvector": "pgvector",

  // ==========================================================================
  // ORMS / QUERY BUILDERS
  // ==========================================================================
  "prisma": "Prisma",
  "typeorm": "TypeORM",
  "sequelize": "Sequelize",
  "drizzle": "Drizzle ORM",
  "drizzle orm": "Drizzle ORM",
  "mongoose": "Mongoose",
  "knex": "Knex.js",
  "knex.js": "Knex.js",
  "sqlalchemy": "SQLAlchemy",
  "hibernate": "Hibernate",
  "entity framework": "Entity Framework",
  "entity framework core": "Entity Framework Core",
  "ef core": "Entity Framework Core",
  "gorm": "GORM",
  "active record": "Active Record",
  "activerecord": "Active Record",

  // ==========================================================================
  // SEARCH ENGINES
  // ==========================================================================
  "elasticsearch": "Elasticsearch",
  "elastic search": "Elasticsearch",
  "opensearch": "OpenSearch",
  "solr": "Apache Solr",
  "apache solr": "Apache Solr",
  "algolia": "Algolia",
  "meilisearch": "Meilisearch",
  "typesense": "Typesense",

  // ==========================================================================
  // MESSAGE BROKERS / STREAMING
  // ==========================================================================
  "kafka": "Apache Kafka",
  "apache kafka": "Apache Kafka",
  "rabbitmq": "RabbitMQ",
  "rabbit mq": "RabbitMQ",
  "activemq": "Apache ActiveMQ",
  "nats": "NATS",
  "zeromq": "ZeroMQ",
  "amazon sqs": "Amazon SQS",
  "sqs": "Amazon SQS",
  "amazon sns": "Amazon SNS",
  "sns": "Amazon SNS",
  "pubsub": "Google Cloud Pub/Sub",
  "pub/sub": "Google Cloud Pub/Sub",
  "google pubsub": "Google Cloud Pub/Sub",
  "apache pulsar": "Apache Pulsar",
  "pulsar": "Apache Pulsar",
  "apache flink": "Apache Flink",
  "flink": "Apache Flink",
  "apache storm": "Apache Storm",
  "storm": "Apache Storm",
  "apache spark": "Apache Spark",
  "spark": "Apache Spark",
  "pyspark": "PySpark",
  "spark streaming": "Spark Streaming",

  // ==========================================================================
  // BIG DATA / DATA ENGINEERING
  // ==========================================================================
  "hadoop": "Apache Hadoop",
  "apache hadoop": "Apache Hadoop",
  "hdfs": "HDFS",
  "hive": "Apache Hive",
  "apache hive": "Apache Hive",
  "pig": "Apache Pig",
  "airflow": "Apache Airflow",
  "apache airflow": "Apache Airflow",
  "dbt": "dbt",
  "databricks": "Databricks",
  "snowflake": "Snowflake",
  "redshift": "Amazon Redshift",
  "amazon redshift": "Amazon Redshift",
  "bigquery": "Google BigQuery",
  "big query": "Google BigQuery",
  "google bigquery": "Google BigQuery",
  "presto": "Presto",
  "trino": "Trino",
  "luigi": "Luigi",
  "nifi": "Apache NiFi",
  "apache nifi": "Apache NiFi",

  // ==========================================================================
  // ANALYTICS / BI
  // ==========================================================================
  "tableau": "Tableau",
  "power bi": "Power BI",
  "powerbi": "Power BI",
  "looker": "Looker",
  "metabase": "Metabase",
  "google analytics": "Google Analytics",
  "mixpanel": "Mixpanel",
  "amplitude": "Amplitude",
  "segment": "Segment",
  "superset": "Apache Superset",
  "apache superset": "Apache Superset",

  // ==========================================================================
  // AI / MACHINE LEARNING / DEEP LEARNING
  // ==========================================================================
  "ai": "Artificial Intelligence",
  "artificial intelligence": "Artificial Intelligence",
  "ml": "Machine Learning",
  "machine learning": "Machine Learning",
  "deep learning": "Deep Learning",
  "tensorflow": "TensorFlow",
  "pytorch": "PyTorch",
  "keras": "Keras",
  "scikit learn": "scikit-learn",
  "scikit-learn": "scikit-learn",
  "sklearn": "scikit-learn",
  "xgboost": "XGBoost",
  "lightgbm": "LightGBM",
  "catboost": "CatBoost",
  "pandas": "pandas",
  "numpy": "NumPy",
  "scipy": "SciPy",
  "opencv": "OpenCV",
  "hugging face": "Hugging Face",
  "huggingface": "Hugging Face",
  "transformers": "Hugging Face Transformers",
  "onnx": "ONNX",
  "mlflow": "MLflow",
  "kubeflow": "Kubeflow",
  "jax": "JAX",
  "theano": "Theano",
  "caffe": "Caffe",

  // ==========================================================================
  // NLP / COMPUTER VISION
  // ==========================================================================
  "nlp": "Natural Language Processing",
  "natural language processing": "Natural Language Processing",
  "computer vision": "Computer Vision",
  "cv": "Computer Vision",
  "spacy": "spaCy",
  "nltk": "NLTK",
  "gensim": "Gensim",
  "yolo": "YOLO",

  // ==========================================================================
  // LLMS / GENERATIVE AI
  // ==========================================================================
  "llm": "Large Language Model",
  "large language model": "Large Language Model",
  "llms": "Large Language Models",
  "generative ai": "Generative AI",
  "genai": "Generative AI",
  "gpt": "GPT",
  "chatgpt": "ChatGPT",
  "openai": "OpenAI",
  "openai api": "OpenAI API",
  "gpt-4": "GPT-4",
  "gpt4": "GPT-4",
  "claude": "Claude",
  "anthropic": "Anthropic",
  "gemini": "Google Gemini",
  "google gemini": "Google Gemini",
  "llama": "Llama",
  "mistral": "Mistral",
  "langchain": "LangChain",
  "langgraph": "LangGraph",
  "llamaindex": "LlamaIndex",
  "llama index": "LlamaIndex",
  "rag": "Retrieval-Augmented Generation",
  "retrieval augmented generation": "Retrieval-Augmented Generation",
  "vector embeddings": "Vector Embeddings",
  "embeddings": "Embeddings",
  "prompt engineering": "Prompt Engineering",
  "fine tuning": "Fine-Tuning",
  "fine-tuning": "Fine-Tuning",
  "stable diffusion": "Stable Diffusion",
  "dall-e": "DALL-E",
  "dalle": "DALL-E",
  "midjourney": "Midjourney",
  "mcp": "Model Context Protocol",
  "model context protocol": "Model Context Protocol",

  // ==========================================================================
  // TESTING
  // ==========================================================================
  "jest": "Jest",
  "vitest": "Vitest",
  "mocha": "Mocha",
  "chai": "Chai",
  "jasmine": "Jasmine",
  "cypress": "Cypress",
  "playwright": "Playwright",
  "selenium": "Selenium",
  "puppeteer": "Puppeteer",
  "testing library": "Testing Library",
  "react testing library": "React Testing Library",
  "rtl": "React Testing Library",
  "enzyme": "Enzyme",
  "junit": "JUnit",
  "testng": "TestNG",
  "pytest": "pytest",
  "unittest": "unittest",
  "rspec": "RSpec",
  "phpunit": "PHPUnit",
  "postman": "Postman",
  "k6": "k6",
  "jmeter": "JMeter",
  "apache jmeter": "JMeter",
  "gatling": "Gatling",
  "cucumber": "Cucumber",
  "bdd": "Behavior-Driven Development",
  "tdd": "Test-Driven Development",

  // ==========================================================================
  // BUILD TOOLS / BUNDLERS
  // ==========================================================================
  "webpack": "Webpack",
  "vite": "Vite",
  "rollup": "Rollup",
  "esbuild": "esbuild",
  "parcel": "Parcel",
  "babel": "Babel",
  "swc": "SWC",
  "turbopack": "Turbopack",
  "gulp": "Gulp",
  "grunt": "Grunt",
  "make": "Make",
  "makefile": "Makefile",
  "maven": "Maven",
  "gradle": "Gradle",
  "ant": "Apache Ant",
  "msbuild": "MSBuild",
  "bazel": "Bazel",
  "nx": "Nx",
  "turborepo": "Turborepo",
  "lerna": "Lerna",

  // ==========================================================================
  // PACKAGE MANAGERS / REGISTRIES
  // ==========================================================================
  "npm": "npm",
  "yarn": "Yarn",
  "pnpm": "pnpm",
  "pip": "pip",
  "conda": "Conda",
  "composer": "Composer",
  "nuget": "NuGet",
  "cargo": "Cargo",
  "gem": "RubyGems",
  "rubygems": "RubyGems",
  "homebrew": "Homebrew",
  "brew": "Homebrew",
  "apt": "APT",
  "yum": "YUM",

  // ==========================================================================
  // RUNTIME ENVIRONMENTS
  // ==========================================================================
  "deno": "Deno",
  "bun": "Bun",
  "jvm": "Java Virtual Machine",
  "java virtual machine": "Java Virtual Machine",
  "jdk": "Java Development Kit",
  "jre": "Java Runtime Environment",
  "wasm": "WebAssembly",
  "webassembly": "WebAssembly",

  // ==========================================================================
  // CLOUD PLATFORMS
  // ==========================================================================
  "aws": "Amazon Web Services",
  "amazon web services": "Amazon Web Services",
  "azure": "Microsoft Azure",
  "microsoft azure": "Microsoft Azure",
  "gcp": "Google Cloud Platform",
  "google cloud": "Google Cloud Platform",
  "google cloud platform": "Google Cloud Platform",
  "digitalocean": "DigitalOcean",
  "digital ocean": "DigitalOcean",
  "linode": "Linode",
  "vultr": "Vultr",
  "oracle cloud": "Oracle Cloud Infrastructure",
  "oci": "Oracle Cloud Infrastructure",
  "ibm cloud": "IBM Cloud",
  "alibaba cloud": "Alibaba Cloud",
  "heroku": "Heroku",
  "vercel": "Vercel",
  "netlify": "Netlify",
  "railway": "Railway",
  "render": "Render",
  "fly.io": "Fly.io",
  "flyio": "Fly.io",
  "cloudflare": "Cloudflare",
  "cloudflare workers": "Cloudflare Workers",
  "cloudflare pages": "Cloudflare Pages",

  // ==========================================================================
  // AWS SERVICES
  // ==========================================================================
  "ec2": "Amazon EC2",
  "amazon ec2": "Amazon EC2",
  "s3": "Amazon S3",
  "amazon s3": "Amazon S3",
  "lambda": "AWS Lambda",
  "aws lambda": "AWS Lambda",
  "ecs": "Amazon ECS",
  "amazon ecs": "Amazon ECS",
  "eks": "Amazon EKS",
  "amazon eks": "Amazon EKS",
  "fargate": "AWS Fargate",
  "cloudfront": "Amazon CloudFront",
  "amazon cloudfront": "Amazon CloudFront",
  "route53": "Amazon Route 53",
  "route 53": "Amazon Route 53",
  "iam": "AWS IAM",
  "aws iam": "AWS IAM",
  "cloudformation": "AWS CloudFormation",
  "cloudwatch": "Amazon CloudWatch",
  "amazon cloudwatch": "Amazon CloudWatch",
  "api gateway": "Amazon API Gateway",
  "amazon api gateway": "Amazon API Gateway",
  "elastic beanstalk": "AWS Elastic Beanstalk",
  "ecr": "Amazon ECR",
  "amazon ecr": "Amazon ECR",

  // ==========================================================================
  // AZURE / GCP SERVICES
  // ==========================================================================
  "azure functions": "Azure Functions",
  "azure devops": "Azure DevOps",
  "azure app service": "Azure App Service",
  "azure kubernetes service": "Azure Kubernetes Service",
  "aks": "Azure Kubernetes Service",
  "azure blob storage": "Azure Blob Storage",
  "gke": "Google Kubernetes Engine",
  "google kubernetes engine": "Google Kubernetes Engine",
  "cloud run": "Google Cloud Run",
  "google cloud run": "Google Cloud Run",
  "cloud functions": "Google Cloud Functions",
  "app engine": "Google App Engine",
  "google app engine": "Google App Engine",

  // ==========================================================================
  // CONTAINERS / ORCHESTRATION
  // ==========================================================================
  "docker": "Docker",
  "docker compose": "Docker Compose",
  "dockerfile": "Dockerfile",
  "kubernetes": "Kubernetes",
  "k8s": "Kubernetes",
  "helm": "Helm",
  "openshift": "OpenShift",
  "rancher": "Rancher",
  "podman": "Podman",
  "containerd": "containerd",
  "istio": "Istio",
  "envoy": "Envoy",
  "service mesh": "Service Mesh",

  // ==========================================================================
  // DEVOPS / CI-CD / INFRASTRUCTURE AS CODE
  // ==========================================================================
  "ci/cd": "CI/CD",
  "cicd": "CI/CD",
  "continuous integration": "Continuous Integration",
  "continuous deployment": "Continuous Deployment",
  "jenkins": "Jenkins",
  "github actions": "GitHub Actions",
  "gitlab ci": "GitLab CI/CD",
  "gitlab ci/cd": "GitLab CI/CD",
  "circleci": "CircleCI",
  "circle ci": "CircleCI",
  "travis ci": "Travis CI",
  "travisci": "Travis CI",
  "teamcity": "TeamCity",
  "bamboo": "Bamboo",
  "argo cd": "Argo CD",
  "argocd": "Argo CD",
  "spinnaker": "Spinnaker",
  "terraform": "Terraform",
  "ansible": "Ansible",
  "puppet": "Puppet",
  "chef": "Chef",
  "pulumi": "Pulumi",
  "vagrant": "Vagrant",
  "packer": "Packer",
  "devops": "DevOps",
  "sre": "Site Reliability Engineering",
  "site reliability engineering": "Site Reliability Engineering",
  "gitops": "GitOps",

  // ==========================================================================
  // MONITORING / LOGGING / OBSERVABILITY
  // ==========================================================================
  "prometheus": "Prometheus",
  "grafana": "Grafana",
  "kibana": "Kibana",
  "logstash": "Logstash",
  "elk stack": "ELK Stack",
  "elk": "ELK Stack",
  "efk stack": "EFK Stack",
  "datadog": "Datadog",
  "new relic": "New Relic",
  "newrelic": "New Relic",
  "splunk": "Splunk",
  "sentry": "Sentry",
  "jaeger": "Jaeger",
  "zipkin": "Zipkin",
  "opentelemetry": "OpenTelemetry",
  "open telemetry": "OpenTelemetry",
  "fluentd": "Fluentd",
  "pagerduty": "PagerDuty",
  "nagios": "Nagios",
  "zabbix": "Zabbix",

  // ==========================================================================
  // WEB SERVERS / PROXIES
  // ==========================================================================
  "nginx": "Nginx",
  "apache": "Apache HTTP Server",
  "apache http server": "Apache HTTP Server",
  "apache2": "Apache HTTP Server",
  "iis": "Internet Information Services",
  "internet information services": "Internet Information Services",
  "caddy": "Caddy",
  "haproxy": "HAProxy",
  "traefik": "Traefik",
  "tomcat": "Apache Tomcat",
  "apache tomcat": "Apache Tomcat",
  "gunicorn": "Gunicorn",
  "uvicorn": "Uvicorn",
  "pm2": "PM2",

  // ==========================================================================
  // CACHING
  // ==========================================================================
  "varnish": "Varnish",
  "cdn": "Content Delivery Network",
  "content delivery network": "Content Delivery Network",

  // ==========================================================================
  // NETWORKING / SECURITY
  // ==========================================================================
  "tcp/ip": "TCP/IP",
  "tcpip": "TCP/IP",
  "http": "HTTP",
  "https": "HTTPS",
  "dns": "DNS",
  "vpn": "VPN",
  "ssl": "SSL",
  "tls": "TLS",
  "ssh": "SSH",
  "firewall": "Firewall",
  "waf": "Web Application Firewall",
  "web application firewall": "Web Application Firewall",
  "penetration testing": "Penetration Testing",
  "pentest": "Penetration Testing",
  "ethical hacking": "Ethical Hacking",
  "owasp": "OWASP",
  "cybersecurity": "Cybersecurity",
  "cyber security": "Cybersecurity",
  "information security": "Information Security",
  "infosec": "Information Security",
  "siem": "SIEM",
  "iam security": "Identity and Access Management",
  "identity and access management": "Identity and Access Management",
  "zero trust": "Zero Trust",
  "vpc": "Virtual Private Cloud",
  "virtual private cloud": "Virtual Private Cloud",

  // ==========================================================================
  // OPERATING SYSTEMS
  // ==========================================================================
  "linux": "Linux",
  "ubuntu": "Ubuntu",
  "debian": "Debian",
  "centos": "CentOS",
  "red hat": "Red Hat Enterprise Linux",
  "rhel": "Red Hat Enterprise Linux",
  "fedora": "Fedora",
  "arch linux": "Arch Linux",
  "windows": "Windows",
  "windows server": "Windows Server",
  "macos": "macOS",
  "mac os": "macOS",
  "osx": "macOS",
  "unix": "Unix",
  "freebsd": "FreeBSD",
  "solaris": "Solaris",

  // ==========================================================================
  // VERSION CONTROL
  // ==========================================================================
  "git": "Git",
  "github": "GitHub",
  "gitlab": "GitLab",
  "bitbucket": "Bitbucket",
  "svn": "Subversion",
  "subversion": "Subversion",
  "mercurial": "Mercurial",
  "perforce": "Perforce",
  "azure repos": "Azure Repos",

  // ==========================================================================
  // MOBILE DEVELOPMENT
  // ==========================================================================
  "android": "Android",
  "ios": "iOS",
  "react native": "React Native",
  "reactnative": "React Native",
  "flutter": "Flutter",
  "swiftui": "SwiftUI",
  "swift ui": "SwiftUI",
  "uikit": "UIKit",
  "jetpack compose": "Jetpack Compose",
  "xamarin": "Xamarin",
  "ionic": "Ionic",
  "cordova": "Apache Cordova",
  "apache cordova": "Apache Cordova",
  "capacitor": "Capacitor",
  "expo": "Expo",

  // ==========================================================================
  // DESKTOP DEVELOPMENT
  // ==========================================================================
  "electron": "Electron",
  "electronjs": "Electron",
  "tauri": "Tauri",
  "qt": "Qt",
  "gtk": "GTK",
  "wpf": "WPF",
  "winforms": "Windows Forms",
  "windows forms": "Windows Forms",
  "javafx": "JavaFX",

  // ==========================================================================
  // GAME DEVELOPMENT
  // ==========================================================================
  "unity": "Unity",
  "unreal engine": "Unreal Engine",
  "unreal": "Unreal Engine",
  "godot": "Godot",
  "cryengine": "CryEngine",
  "cocos2d": "Cocos2d",
  "phaser": "Phaser",
  "directx": "DirectX",
  "opengl": "OpenGL",
  "vulkan": "Vulkan",

  // ==========================================================================
  // AR / VR
  // ==========================================================================
  "ar": "Augmented Reality",
  "augmented reality": "Augmented Reality",
  "vr": "Virtual Reality",
  "virtual reality": "Virtual Reality",
  "mixed reality": "Mixed Reality",
  "arkit": "ARKit",
  "arcore": "ARCore",
  "oculus sdk": "Oculus SDK",
  "webxr": "WebXR",

  // ==========================================================================
  // EMBEDDED / IOT / ROBOTICS
  // ==========================================================================
  "embedded systems": "Embedded Systems",
  "iot": "Internet of Things",
  "internet of things": "Internet of Things",
  "arduino": "Arduino",
  "raspberry pi": "Raspberry Pi",
  "esp32": "ESP32",
  "esp8266": "ESP8266",
  "rtos": "RTOS",
  "freertos": "FreeRTOS",
  "mqtt": "MQTT",
  "robotics": "Robotics",
  "ros": "Robot Operating System",
  "robot operating system": "Robot Operating System",
  "plc": "PLC",
  "scada": "SCADA",

  // ==========================================================================
  // BLOCKCHAIN / WEB3
  // ==========================================================================
  "blockchain": "Blockchain",
  "web3": "Web3",
  "ethereum": "Ethereum",
  "bitcoin": "Bitcoin",
  "smart contracts": "Smart Contracts",
  "hardhat": "Hardhat",
  "truffle": "Truffle",
  "web3.js": "Web3.js",
  "web3js": "Web3.js",
  "ethers.js": "Ethers.js",
  "ethersjs": "Ethers.js",
  "metamask": "MetaMask",
  "ipfs": "IPFS",
  "nft": "NFT",
  "defi": "DeFi",
  "polygon": "Polygon",
  "hyperledger": "Hyperledger",

  // ==========================================================================
  // CMS / E-COMMERCE
  // ==========================================================================
  "wordpress": "WordPress",
  "drupal": "Drupal",
  "joomla": "Joomla",
  "contentful": "Contentful",
  "sanity": "Sanity",
  "strapi": "Strapi",
  "ghost": "Ghost",
  "shopify": "Shopify",
  "magento": "Magento",
  "woocommerce": "WooCommerce",
  "bigcommerce": "BigCommerce",
  "prestashop": "PrestaShop",

  // ==========================================================================
  // DESIGN TOOLS
  // ==========================================================================
  "figma": "Figma",
  "sketch": "Sketch",
  "adobe xd": "Adobe XD",
  "adobe photoshop": "Adobe Photoshop",
  "photoshop": "Adobe Photoshop",
  "adobe illustrator": "Adobe Illustrator",
  "illustrator": "Adobe Illustrator",
  "invision": "InVision",
  "zeplin": "Zeplin",
  "canva": "Canva",

  // ==========================================================================
  // NO-CODE / LOW-CODE
  // ==========================================================================
  "webflow": "Webflow",
  "bubble": "Bubble",
  "zapier": "Zapier",
  "airtable": "Airtable",
  "retool": "Retool",
  "n8n": "n8n",
  "power automate": "Power Automate",
  "power apps": "Power Apps",
  "appsheet": "AppSheet",
  "make.com": "Make",
  "integromat": "Make",

  // ==========================================================================
  // DEVELOPER TOOLS / EDITORS / IDES
  // ==========================================================================
  "vscode": "Visual Studio Code",
  "vs code": "Visual Studio Code",
  "visual studio code": "Visual Studio Code",
  "visual studio": "Visual Studio",
  "intellij": "IntelliJ IDEA",
  "intellij idea": "IntelliJ IDEA",
  "webstorm": "WebStorm",
  "pycharm": "PyCharm",
  "eclipse": "Eclipse",
  "netbeans": "NetBeans",
  "android studio": "Android Studio",
  "xcode": "Xcode",
  "vim": "Vim",
  "neovim": "Neovim",
  "emacs": "Emacs",
  "sublime text": "Sublime Text",
  "atom": "Atom",
  "postman api": "Postman",
  "insomnia": "Insomnia",
  "docker desktop": "Docker Desktop",

  // ==========================================================================
  // DOCUMENTATION
  // ==========================================================================
  "confluence": "Confluence",
  "notion": "Notion",
  "jsdoc": "JSDoc",
  "swagger ui": "Swagger UI",
  "docusaurus": "Docusaurus",
  "gitbook": "GitBook",
  "storybook": "Storybook",

  // ==========================================================================
  // PROJECT MANAGEMENT / COLLABORATION
  // ==========================================================================
  "jira": "Jira",
  "trello": "Trello",
  "asana": "Asana",
  "monday.com": "Monday.com",
  "slack": "Slack",
  "microsoft teams": "Microsoft Teams",
  "agile": "Agile",
  "scrum": "Scrum",
  "kanban": "Kanban",
  "waterfall": "Waterfall",

  // ==========================================================================
  // ARCHITECTURE / PATTERNS
  // ==========================================================================
  "microservices": "Microservices",
  "monolith": "Monolithic Architecture",
  "serverless": "Serverless",
  "event driven architecture": "Event-Driven Architecture",
  "event-driven architecture": "Event-Driven Architecture",
  "mvc": "MVC",
  "mvvm": "MVVM",
  "clean architecture": "Clean Architecture",
  "domain driven design": "Domain-Driven Design",
  "ddd": "Domain-Driven Design",
  "cqrs": "CQRS",
  "solid principles": "SOLID Principles",
  "design patterns": "Design Patterns",
} as const;

export type TechnologyAliasKey = keyof typeof TECHNOLOGY_ALIASES;
export type TechnologyCanonicalName = (typeof TECHNOLOGY_ALIASES)[TechnologyAliasKey];
